//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuickCheck_AngularEntities : DbContext
    {
        public QuickCheck_AngularEntities()
            : base("name=QuickCheck_AngularEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Icon> Tbl_Icon { get; set; }
        public virtual DbSet<Tbl_Links> Tbl_Links { get; set; }
        public virtual DbSet<TblParentMenu> TblParentMenus { get; set; }
        public virtual DbSet<TblRoleMaster> TblRoleMasters { get; set; }
        public virtual DbSet<TblRoleLinkBinding> TblRoleLinkBindings { get; set; }
    }
}
