//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAllBulkMandate
    {
        public long AllBulkMandateId { get; set; }
        public string Frequency { get; set; }
        public string DebitType { get; set; }
        public Nullable<System.DateTime> DateOnMandate { get; set; }
        public string Refrence1 { get; set; }
        public string BankReturnCustNme { get; set; }
        public string IsBankOrMandateName { get; set; }
        public string Refrence2 { get; set; }
        public string PhoneNumber { get; set; }
        public string Customer2 { get; set; }
        public Nullable<long> ScanCount { get; set; }
        public Nullable<long> PrintCount { get; set; }
        public string TIPPath { get; set; }
        public string JPGPath { get; set; }
        public string Customer3 { get; set; }
        public string Customer1 { get; set; }
        public string EntityId { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string AmountRupeesInWords { get; set; }
        public Nullable<decimal> AmountRupees { get; set; }
        public string BankName { get; set; }
        public string EmailId { get; set; }
        public string AcNo { get; set; }
        public string IFSC { get; set; }
        public string ToDebit { get; set; }
        public Nullable<double> MICR { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
