//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbankData
    {
        public long BankDataId { get; set; }
        public Nullable<long> ClientDataId { get; set; }
        public string AccountNo { get; set; }
        public string BenificiaryName { get; set; }
        public string RefId { get; set; }
        public string IFSCcode { get; set; }
        public string MICRcode { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string UniqueNo { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
