//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankHeader
    {
        public string BankCode { get; set; }
        public Nullable<double> BankID { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> Is_Sub_Member { get; set; }
        public Nullable<bool> Is_IMPS_Live { get; set; }
        public Nullable<bool> Is_NACH_Live { get; set; }
        public Nullable<bool> Is_eNACH_Live { get; set; }
        public Nullable<bool> Is_APBS { get; set; }
        public Nullable<int> Bank_IIN { get; set; }
        public string NetBanking { get; set; }
        public string DebitCard { get; set; }
        public Nullable<bool> Is_UPI { get; set; }
        public bool IsNetBanking_Sponsor { get; set; }
        public bool IsDebitCard_Sponsor { get; set; }
    }
}
