//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankIMP
    {
        public long BankIMPSId { get; set; }
        public string BenificiaryName { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string MICRCode { get; set; }
        public string AccountNo { get; set; }
        public Nullable<bool> IsPrintStatus { get; set; }
        public string IsPrint { get; set; }
        public Nullable<bool> IsPrintforEmail { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
