//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblclientData
    {
        public long ClientDataId { get; set; }
        public string AccountNo { get; set; }
        public string BenificiaryName { get; set; }
        public string RefId { get; set; }
        public string SponserBankCode { get; set; }
        public string UtilityCode { get; set; }
        public string CreatedStatus { get; set; }
        public string CompanyName { get; set; }
        public string BankName { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string DebitTo { get; set; }
        public string UniqueNo { get; set; }
        public string IFSCcode { get; set; }
        public string MICRcode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Frequency { get; set; }
        public string DebitType { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string PhoneNo { get; set; }
        public string EmailId { get; set; }
        public string RefEmailId { get; set; }
        public Nullable<System.DateTime> PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public string IsMerged { get; set; }
        public string status { get; set; }
        public Nullable<long> transactioncount { get; set; }
        public string TransactionStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
