//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEsignResponse
    {
        public long EsignResponseId { get; set; }
        public Nullable<long> MandateId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> status { get; set; }
        public string ErrorCode { get; set; }
        public string ApplicationId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string filename { get; set; }
        public string savepath { get; set; }
    }
}
