//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityBusinessCode
    {
        public long EntityBusinessCodeId { get; set; }
        public string EntityBusinessCode { get; set; }
        public string Code { get; set; }
    }
}
