//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityCategoryCode
    {
        public long categoryId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string code { get; set; }
        public string category_name { get; set; }
    }
}
