//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntity
    {
        public long EntityId { get; set; }
        public string code { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string SponsorBankCode { get; set; }
        public string PeriodType { get; set; }
        public string FrequencyType { get; set; }
        public string ToDebit { get; set; }
        public string DebitType { get; set; }
        public string UtilityCode { get; set; }
        public string SponsorBankName { get; set; }
        public Nullable<bool> IsAllowENachMobile { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string InstructingMemberId { get; set; }
        public string ModeOfPayment { get; set; }
        public string AmountBank_Mandate { get; set; }
        public string EntityBusinessCode { get; set; }
        public Nullable<bool> IsValidationCountEnable { get; set; }
        public Nullable<long> BankValidationUserCount { get; set; }
        public Nullable<long> BankValidationAdminCount { get; set; }
        public Nullable<long> AcValidationUserCount { get; set; }
        public Nullable<long> AcValidationAdminCount { get; set; }
        public Nullable<bool> IsRefrenceNumeric { get; set; }
        public Nullable<bool> IsSendEmailCustomer { get; set; }
        public Nullable<bool> IsShowMandateMode { get; set; }
        public Nullable<bool> IsEmandate { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public Nullable<bool> IsRefrence2Mandatory { get; set; }
        public Nullable<bool> IsThirdTransaction { get; set; }
        public Nullable<bool> IsZipShorABPS { get; set; }
        public Nullable<bool> ISTodateMandatoryEnach { get; set; }
        public Nullable<bool> CheckerRequired { get; set; }
        public Nullable<bool> isaccountvalidation { get; set; }
        public Nullable<bool> CheckerRecheck { get; set; }
        public string AccountNumber { get; set; }
        public string PresentmentNoSequence { get; set; }
        public string mandatemode { get; set; }
        public string isphysicalmandate { get; set; }
        public string isnetbacking { get; set; }
        public string isdebitcard { get; set; }
        public string isaadhar { get; set; }
        public string ResponseURL { get; set; }
        public string AppId { get; set; }
        public string EnitityMarchantKey { get; set; }
        public string UserNameHeader { get; set; }
        public string UserNameDetail { get; set; }
        public Nullable<bool> IsShowConsent { get; set; }
        public Nullable<int> NoOfQRCopy { get; set; }
        public Nullable<bool> IsSendUMRN { get; set; }
        public string EncryptionKey { get; set; }
        public Nullable<bool> IsEmandateSms { get; set; }
    }
}
