//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEsignErrorMandateLog
    {
        public long EsignErrorMandateLogId { get; set; }
        public Nullable<long> MandateId { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public string MessageId { get; set; }
        public string CreationDatetime { get; set; }
        public string ErrorCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
    }
}
