//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFILESEQUENCE
    {
        public long NumberSequenceId { get; set; }
        public string SEQ1 { get; set; }
        public string SEQ2 { get; set; }
        public string SEQ3 { get; set; }
        public string SEQ4 { get; set; }
        public string SEQ5 { get; set; }
        public string SEQ6 { get; set; }
        public string SEQ7 { get; set; }
        public string SEQ8 { get; set; }
        public string SEQ9 { get; set; }
        public string SEQ10 { get; set; }
        public string SEQ11 { get; set; }
        public string SEQ12 { get; set; }
        public string SEQ13 { get; set; }
        public string SEQ14 { get; set; }
        public string SEQ15 { get; set; }
        public string BankID { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string RuntimeIncrementNo { get; set; }
    }
}
