//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIFSCBank
    {
        public long ID { get; set; }
        public string BANK { get; set; }
        public string IFSC { get; set; }
        public Nullable<double> MICR { get; set; }
        public string BRANCH { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<double> CONTACT { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string STATE { get; set; }
        public Nullable<bool> IsNachLive { get; set; }
        public Nullable<bool> IsIMPSLive { get; set; }
    }
}
