//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllogMandate
    {
        public long LogMandateId { get; set; }
        public Nullable<long> MandateId { get; set; }
        public string Frequency { get; set; }
        public Nullable<System.DateTime> DateOnMandate { get; set; }
        public string DebitType { get; set; }
        public string Refrence1 { get; set; }
        public string Refrence2 { get; set; }
        public string Customer2 { get; set; }
        public string Customer3 { get; set; }
        public string Customer1 { get; set; }
        public string PhoneNumber { get; set; }
        public string EntityId { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string AmountRupeesInWords { get; set; }
        public string AmountRupees { get; set; }
        public string BankName { get; set; }
        public string EmailId { get; set; }
        public string AcNo { get; set; }
        public string IFSC { get; set; }
        public string ToDebit { get; set; }
        public Nullable<double> MICR { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string UtilityCode { get; set; }
        public string SponsorbankCode { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public string BankReturnCustNme { get; set; }
        public string IsBankOrMandateName { get; set; }
        public string RejectedReason { get; set; }
        public bool IsExcelMandateDownload { get; set; }
        public bool IsSnapMandateDownload { get; set; }
        public bool IsRejected { get; set; }
        public string EnachMobileNo { get; set; }
        public string EnachAdharNo { get; set; }
        public string EnachEmail { get; set; }
        public Nullable<bool> IsFirstValidation { get; set; }
        public Nullable<bool> IsSecondValidation { get; set; }
        public string FileUploadedCount { get; set; }
        public Nullable<long> BankValidationUserCount1 { get; set; }
        public Nullable<long> BankValidationAdminCount1 { get; set; }
        public Nullable<long> AcValidationUserCount1 { get; set; }
        public Nullable<long> AcValidationAdminCount1 { get; set; }
        public Nullable<bool> IsFinalReject { get; set; }
        public string AutoRejectReason { get; set; }
        public Nullable<long> BankValidationUserCount { get; set; }
        public Nullable<long> BankValidationAdminCount { get; set; }
        public Nullable<long> AcValidationUserCount { get; set; }
        public Nullable<long> AcValidationAdminCount { get; set; }
        public string MandateMode { get; set; }
        public string MandateModeRadio { get; set; }
        public string MSGId { get; set; }
        public string NPCIMsgId { get; set; }
        public string CategoryCode { get; set; }
    }
}
