//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogTransaction
    {
        public long logtransId { get; set; }
        public Nullable<long> MergeDataId { get; set; }
        public string LastAccountNo { get; set; }
        public string UpdateAccountNo { get; set; }
        public string LastBenificiaryName { get; set; }
        public string UpdateBenificiaryName { get; set; }
        public string LastRefId { get; set; }
        public string UpdateRefId { get; set; }
        public string LastSponserBankCode { get; set; }
        public string UpdateSponserBankCode { get; set; }
        public string LastUtilityCode { get; set; }
        public string UpdateUtilityCode { get; set; }
        public string LastCreatedStatus { get; set; }
        public string UpdateCreatedStatus { get; set; }
        public string LastCompanyName { get; set; }
        public string UpdateCompanyName { get; set; }
        public string LastBankName { get; set; }
        public string UpdateBankName { get; set; }
        public Nullable<long> LastBranchId { get; set; }
        public Nullable<long> UpdateBranchId { get; set; }
        public string LastDebitTo { get; set; }
        public string UpdateDebitTo { get; set; }
        public Nullable<long> LastUniqueNo { get; set; }
        public Nullable<long> UpdateUniqueNo { get; set; }
        public Nullable<decimal> LastAmount { get; set; }
        public Nullable<decimal> UpdateAmount { get; set; }
        public string LastFrequency { get; set; }
        public string UpdateFrequency { get; set; }
        public string LastDebitType { get; set; }
        public string UpdateDebitType { get; set; }
        public string LastReference1 { get; set; }
        public string UpdateReference1 { get; set; }
        public string LastReference2 { get; set; }
        public string UpdateReference2 { get; set; }
        public string LastPhoneNo { get; set; }
        public string UpdatePhoneNo { get; set; }
        public string LastEmailId { get; set; }
        public string UpdateEmailId { get; set; }
        public string LastRefEmailId { get; set; }
        public string UpdateRefEmailId { get; set; }
        public Nullable<System.DateTime> LastPeriodFrom { get; set; }
        public Nullable<System.DateTime> UpdatePeriodFrom { get; set; }
        public Nullable<System.DateTime> LastPeriodTo { get; set; }
        public Nullable<System.DateTime> UpdatePeriodTo { get; set; }
        public string LastIsMerged { get; set; }
        public string UpdateIsMerged { get; set; }
        public string LastIFSCcode { get; set; }
        public string UpdateIFSCcode { get; set; }
        public string LastMICRcode { get; set; }
        public string UpdateMICRcode { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
