//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLoginSessionTrxn
    {
        public long LoginSesionID { get; set; }
        public int UserID { get; set; }
        public string TokenID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public bool IsIdealLogout { get; set; }
        public bool IsSessionActive { get; set; }
        public System.DateTime MeanTime { get; set; }
    }
}
