//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLegacyHeader
    {
        public long UploadHeaderId { get; set; }
        public string UploadNo { get; set; }
        public string FileName { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<long> ReqCount { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> PrsentmentDate { get; set; }
        public string BankName { get; set; }
        public Nullable<long> TotalCount { get; set; }
        public Nullable<long> Successdata { get; set; }
        public string legacyUploadedID { get; set; }
        public Nullable<long> EntityID { get; set; }
    }
}
