//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMergedData
    {
        public long MergeDataId { get; set; }
        public long ClientDataId { get; set; }
        public long BankDataId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<long> UniqueNo { get; set; }
        public bool IsMailSent { get; set; }
        public Nullable<long> EditCount { get; set; }
        public Nullable<long> TransactionCount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
