//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNPCIResponseHDFC
    {
        public long ResponseID { get; set; }
        public string MandateDate { get; set; }
        public string SponsorBankCode { get; set; }
        public string ClientNumber { get; set; }
        public string NameofCompany { get; set; }
        public string Action { get; set; }
        public string AcType { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string DebitMaxAmt { get; set; }
        public string Amount { get; set; }
        public string ReferenceNumber { get; set; }
        public string SchemePlanReferenceNo { get; set; }
        public string Frequency { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string AccountHolderName { get; set; }
        public string CustomerAdditionalInformation { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNumber { get; set; }
        public string EMailID { get; set; }
        public string ImageName { get; set; }
        public string UMRNNo { get; set; }
        public string MandateStatus { get; set; }
        public string RejectionCode { get; set; }
        public string RejectionReason { get; set; }
        public string InitialRejectReason { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PocessDate { get; set; }
    }
}
