//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresentmentResponseHeader
    {
        public long ResheaderId { get; set; }
        public Nullable<long> APBStransactioncode { get; set; }
        public string Control7 { get; set; }
        public string UserName { get; set; }
        public string Control14 { get; set; }
        public string ACHFileNo { get; set; }
        public string Control19 { get; set; }
        public string Control15 { get; set; }
        public string LedgerFolioNumber { get; set; }
        public string UserDefinedlimitforindividualitems13 { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string SettlementDate { get; set; }
        public string Reservedkeptblankbyuser { get; set; }
        public string Filler3 { get; set; }
        public string UserNumber { get; set; }
        public string UserReference { get; set; }
        public string SponsorBankIFSCMICRIIN { get; set; }
        public string DestinationBankIIN { get; set; }
        public string UserBankAccountNumber { get; set; }
        public Nullable<long> TotalItems { get; set; }
        public string SettlementCycleKeptblankbyUser { get; set; }
        public string Filler57 { get; set; }
        public string Reservedkeptblankbyuser101 { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string FileName { get; set; }
    }
}
