//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentMode
    {
        public long PaymentModeId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BranchName { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> mandateId { get; set; }
    }
}
