//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRoleMaster
    {
        public int RoleID { get; set; }
        public int RoleType { get; set; }
        public string RoleName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Createdon { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int Createdby { get; set; }
        public int Updatedby { get; set; }
    }
}
