//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceLog
    {
        public long ServiceLogID { get; set; }
        public string LogDescription { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
    }
}
