//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKotakBillingReport
    {
        public string MandateStatus { get; set; }
        public string Remark { get; set; }
        public string DateonMandate { get; set; }
        public string SponsorbankCode { get; set; }
        public string UtilityCode { get; set; }
        public string IWeherebyAuthorize { get; set; }
        public string ToDebit { get; set; }
        public string BankacNumber { get; set; }
        public string BankName { get; set; }
        public string IFSC { get; set; }
        public Nullable<double> MICR { get; set; }
        public string Amount { get; set; }
        public string Frequency { get; set; }
        public string DebitType { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
        public string Fromm { get; set; }
        public string Too { get; set; }
        public string NameasinBankRecords1 { get; set; }
        public string NameasinBankRecords2 { get; set; }
        public string NameasinBankRecords3 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ActivityName { get; set; }
        public long MandateId { get; set; }
        public long ActivityId { get; set; }
        public string MandateMode { get; set; }
        public string UserType { get; set; }
    }
}
